title: JFDTEST TITLE
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8566308
  brandStrength: 0.8018681679386646
  lightness: 0.8064516
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  rhythmicContrast: 0.9014337
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: jfdtest
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.05667391209863126
layout_spectrum: 0.07168459
